import type { NextPage } from "next";
import Head from "next/head";
import { Container, Loading, Text } from "@nextui-org/react";

import { CategorySelector } from "components/category-selector";
import { useCategories } from "hooks/use-shopping";
import { USER_FEEDBACK_ROLE } from "testing-utils/variables";

import styles from "styles/routes/home.module.css";

export const Shopping: NextPage = () => {
  const { data: categories, isLoading } = useCategories();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Container xl>
          <Text h1 className={styles.title}>
            Shopping lists
          </Text>
          {isLoading && (
            <Loading role="alert" data-testid={USER_FEEDBACK_ROLE}>
              Loading
            </Loading>
          )}
          {!!categories?.length && <CategorySelector categories={categories} />}
        </Container>
      </main>
    </>
  );
};
