import type { NextPage } from "next";
import Head from "next/head";
import { Text } from "@nextui-org/react";

import { CategorySelector } from "components/category-selector";

import styles from "styles/routes/home.module.css";

export const Shopping: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Text h1 className={styles.title}>
          Shopping lists
        </Text>
        <CategorySelector
          categories={["Outdoor", "Office", "Indoor", "Green"]}
        />
      </main>
    </div>
  );
};
