import type { NextPage } from "next";
import Head from "next/head";
import { Container, Text } from "@nextui-org/react";

import { fakeCategories } from "testing-utils/mocks/shopping";
import { CategorySelector } from "components/category-selector";

import styles from "styles/routes/home.module.css";

export const Shopping: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Container xl>
          <Text h1 className={styles.title}>
            Shopping lists
          </Text>
          <CategorySelector categories={fakeCategories} />
        </Container>
      </main>
    </>
  );
};
