import type { NextPage } from "next";
import Head from "next/head";

import { Logo } from "components/logo";

import styles from "styles/pages/home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <Logo />
        </h1>
      </main>
    </div>
  );
};

export default Home;
